### ISSUE TITLE
rtlsdr_wsprd  calibration help please

### ISSUE THREAD

**Issue by bradshawlupton** [sharjeelaziz/wspr-receiver#1]
I am 100' from my WSPR beacon, which is getting over 700 spots per day.

The instructions beautifully built the rtlsdr_wsprd 

GQRX loudly hears both my WSPR beacon and the pico-cw-beacon in my attic attic, both on 10m

I calibrated the both transmit beacons with a pico frequency counter GPS standard fro  vu3cer Dhiru Kholia (neat stuff)

          https://github.com/kholia/pico-cw-beacon-drs 
                   and
         https://github.com/kholia/pico_ft8_xcvr

=============== results

I have to believe that I have a calibration of the receiver step to add in. a 600 hz band is so terribly tiny.  How may I confirm the  crummy cheapest rtl-sdr is within a few Hz of correct?

=============== results

/home/bbl/SW/rtlsdr-wsprd/rtlsdr_wsprd -f 28.1246M -c wb2tev -l FN41 a.1 -d 2
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R828D tuner
Enabled direct sampling mode, input 2

Starting rtlsdr-wsprd (2022-10-14, 12:29z) -- Version 0.5.4
  Callsign     : wb2tev
  Locator      : FN41
  Dial freq.   : 28124600 Hz
  Real freq.   : 28124600 Hz
  PPM factor   : 0
  Gain         : 29 dB
Wait for time sync (start in 6 sec)

              Date  Time(z)    SNR     DT       Freq Dr    Call    Loc Pwr
No spot 2022-10-14 12:30z
No spot 2022-10-14 12:32z
No spot 2022-10-14 12:34z
No spot 2022-10-14 12:36z
No spot 2022-10-14 12:38z
No spot 2022-10-14 12:40z

**Comment by sharjeelaziz** [comment]
@bradshawlupton Sorry, at the moment I am not very current on this. Have not done this in a while. Would have loved to help.

**Comment by bradshawlupton** [comment]
thank you, I am learning the calibration tricks, and will post them here soon.  been transmitting spots for three years,  It was about time to master understanding and watching my spots, from 100' away.  I moved to 10m as the chaeap cheap $9 rtl_sdr starts at 27 mhz, and is dynamite at 100' and a 1/2 wave dipole, k1te bradshaw
